version: "3.9"

services:
  Riakmaw:
    image: riakmaw
    container_name: RiakmawBot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERBOTINDO_ACCESS_TOKEN=${USERBOTINDO_ACCESS_TOKEN}
    ports:
      - 8000:8000
    env_file:
      - config.env
    restart: unless-stopped

# # Uncomment the following lines to use a local MongoDB database
# # aware that some feature will not work as Riakmaw expect a MongoDB that support ReplicaSet!
# # This lines bellow only uses a single MongoDB instance for simplicity
# # Change it to your needs if you want to convert it to a ReplicaSet

#     depends_on:
#       - mongo
#     environment:
#       DB_URI: "mongodb://Riakmaw:mypasswd@mongo"

#   mongo:
#     image: "mongo:latest"
#     container_name: RiakmawMongo
#     volumes:
#       - "mongo_Riakmaw:/data/db"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: Riakmaw
#       MONGO_INITDB_ROOT_PASSWORD: mypasswd

# volumes:
#   mongo_Riakmaw:
